---
sidebar: sidebar 
permalink: concept-kubernetes.html 
keywords: kubernetes, k8s, back up kubernetes, back up k8s, discover kubernetes cluster, discover k8s, amazon eks, eks, azure, aks, back up persistent volumes, persistent volumes, kubernetes support 
summary: Astra Trident 是由 NetApp 维护的一个完全受支持的开源项目。Astra Trident 与 Kubernetes 及其永久性卷框架本机集成，可从运行任意 NetApp 存储平台组合的系统无缝配置和管理卷。 
---
= Kubernetes 在 Cloud Manager 中进行数据管理
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Astra Trident 是由 NetApp 维护的一个完全受支持的开源项目。Astra Trident 与 Kubernetes 及其永久性卷框架本机集成，可从运行任意 NetApp 存储平台组合的系统无缝配置和管理卷。 link:https://docs.netapp.com/us-en/trident/index.html["了解有关 Trident 的更多信息"^]。



== 功能

您可以使用 Cloud Manager 直接管理 Kubernetes 集群。

* 安装 Astra Trident 。
* 在混合云基础架构中添加和管理集群。
* 添加和管理存储类并将其连接到工作环境。
* 使用 Cloud Backup Service 备份永久性卷。




== 支持的 Kubernetes 部署

Cloud Manager 支持在以下环境中运行的受管 Kubernetes 集群：

* link:../requirements/kubernetes-reqs-aws.html["Amazon Elastic Kubernetes Service （ Amazon EKS ）"]
* link:../requirements/kubernetes-reqs-aks.html["Microsoft Azure Kubernetes Service （ AKS ）"]
* link:../requirements/kubernetes-reqs-gke.html["Google Kubernetes Engine （ GKEE ）"]




== 支持的 Astra Trident 部署

需要使用四个最新版本的 Astra Trident 之一。您可以直接从 Cloud Manager 安装 Astra Trident 。您应该 link:https://docs.netapp.com/us-en/trident/trident-get-started/requirements.html["查看前提条件"^] 安装前。

要升级 Astra Trident ， link:https://docs.netapp.com/us-en/trident/trident-managing-k8s/upgrade-operator.html["使用操作员升级"^]。



== 支持的后端存储

必须在每个 Kubernetes 集群上安装 NetApp 的 Astra Trident ，并且必须将 Cloud Volumes ONTAP 配置为集群的后端存储。



== 成本

在 Cloud Manager 中发现您的 Kubernetes 集群不收取任何费用，但在使用 Cloud Backup Service 备份永久性卷时，系统会向您收取费用。
